select
    {{ transform_null_binary("fumador") }} as fumador,
    {{ transform_null_binary("bebedor") }} as bebedor,
    {{ transform_null_binary("proc_quirurgico_traumatismo") }} as proc_quirurgico_traumatismo,
    {{ transform_null_binary("inmovilidad_m_inferiores") }} as inmovilidad_m_inferiores,
    {{ transform_null_binary("viaje_prolongado") }} as viaje_prolongado,
    {{ transform_null_binary("tep_tvp_previo") }} as tep_tvp_previo,
    {{ transform_null_binary("malignidad") }} as malignidad,
    {{ transform_null_binary("disnea") }} as disnea,
    {{ transform_null_binary("dolor_toracico") }} as dolor_toracico,
    {{ transform_null_binary("tos") }} as tos,
    {{ transform_null_binary("hemoptisis") }} as hemoptisis,
    {{ transform_null_binary("sintomas_disautonomicos") }} as sintomas_disautonomicos,
    {{ transform_null_binary("edema_m_inferiores") }} as edema_m_inferiores,
    {{ transform_null_binary("crepitaciones") }} as crepitaciones,
    {{ transform_null_binary("sibilancias") }} as sibilancias,
    {{ transform_null_binary("soplos") }} as soplos,
    {{ transform_null_binary("derrame") }} as derrame,
    {{ transform_null_binary("fiebre")}} as fiebre,
    {{ transform_null_numeric("edad")}} as edad,
    {{ transform_null_numeric("frecuencia_respiratoria")}} as frecuencia_respiratoria,
    {{ transform_null_numeric("wbc")}} as wbc,
    {{ transform_null_numeric("saturacion_sangre")}} as saturacion_sangre,
    {{ transform_null_numeric("frecuencia_cardiaca")}} as frecuencia_cardiaca,
    {{ transform_null_numeric("presion_sistolica")}} as presion_sistolica,
    {{ transform_null_numeric("presion_diastolica")}} as presion_diastolica,
    {{ transform_null_numeric("hb")}} as hb,
    {{ transform_null_numeric("plt")}} as plt,
    otra_enfermedad,
    enfermedad_hematologica,
    enfermedad_cardiaca,
    enfermedad_endocrina,
    enfermedad_gastrointestinal,
    enfermedad_hepatopatia_cronica,
    enfermedad_neurologica,
    enfermedad_pulmonar,
    enfermedad_renal,
    enfermedad_trombofilia,
    enfermedad_urologica,
    enfermedad_vascular,
    enfermedad_vih,
    enfermedad_diabetes_mellitus,
    enfermedad_coronaria,
    enfermedad_hipertension_arterial,
from {{ ref("silver_data") }}