select
    id,
    genero,
    otra_enfermedad,
    tep,

    {{ transform_null_binary(ref("silver"), "fumador") }} as fumador,
    {{ transform_null_binary(ref("silver"), "bebedor") }} as bebedor,
    {{ transform_null_binary(ref("silver"), "proc_quirurgico_traumatismo") }} as proc_quirurgico_traumatismo,
    {{ transform_null_binary(ref("silver"), "inmovilidad_m_inferiores") }} as inmovilidad_m_inferiores,
    {{ transform_null_binary(ref("silver"), "viaje_prolongado") }} as viaje_prolongado,
    {{ transform_null_binary(ref("silver"), "tep_tvp_previo") }} as tep_tvp_previo,
    {{ transform_null_binary(ref("silver"), "malignidad") }} as malignidad,
    {{ transform_null_binary(ref("silver"), "disnea") }} as disnea,
    {{ transform_null_binary(ref("silver"), "dolor_toracico") }} as dolor_toracico,
    {{ transform_null_binary(ref("silver"), "tos") }} as tos,
    {{ transform_null_binary(ref("silver"), "hemoptisis") }} as hemoptisis,
    {{ transform_null_binary(ref("silver"), "sintomas_disautonomicos") }} as sintomas_disautonomicos,
    {{ transform_null_binary(ref("silver"), "edema_m_inferiores") }} as edema_m_inferiores,
    {{ transform_null_binary(ref("silver"), "crepitaciones") }} as crepitaciones,
    {{ transform_null_binary(ref("silver"), "sibilancias") }} as sibilancias,
    {{ transform_null_binary(ref("silver"), "soplos") }} as soplos,
    {{ transform_null_binary(ref("silver"), "derrame") }} as derrame,
    {{ transform_null_binary(ref("silver"), "fiebre")}} as fiebre,
    {{ transform_null_numeric(ref("silver"), "edad") }} as edad,
    {{ transform_null_numeric(ref("silver"), "frecuencia_respiratoria") }} as frecuencia_respiratoria,
    {{ transform_null_numeric(ref("silver"), "wbc") }} as wbc,
    {{ transform_null_numeric(ref("silver"), "saturacion_sangre") }} as saturacion_sangre,
    {{ transform_null_numeric(ref("silver"), "frecuencia_cardiaca") }} as frecuencia_cardiaca,
    {{ transform_null_numeric(ref("silver"), "presion_sistolica") }} as presion_sistolica,
    {{ transform_null_numeric(ref("silver"), "presion_diastolica") }} as presion_diastolica,
    {{ transform_null_numeric(ref("silver"), "hb") }} as hb,
    {{ transform_null_numeric(ref("silver"), "plt") }} as plt,

    coalesce(enfermedad_hematologica, 0) as enfermedad_hematologica,
    coalesce(enfermedad_cardiaca, 0) as enfermedad_cardiaca,
    coalesce(enfermedad_endocrina, 0) as enfermedad_endocrina,
    coalesce(enfermedad_gastrointestinal, 0) as enfermedad_gastrointestinal,
    coalesce(enfermedad_hepatopatia_cronica, 0) as enfermedad_hepatopatia_cronica,
    coalesce(enfermedad_neurologica, 0) as enfermedad_neurologica,
    coalesce(enfermedad_pulmonar, 0) as enfermedad_pulmonar,
    coalesce(enfermedad_renal, 0) as enfermedad_renal,
    coalesce(enfermedad_trombofilia, 0) as enfermedad_trombofilia,
    coalesce(enfermedad_urologica, 0) as enfermedad_urologica,
    coalesce(enfermedad_vascular, 0) as enfermedad_vascular,
    coalesce(enfermedad_vih, 0) as enfermedad_vih,
    coalesce(enfermedad_diabetes_mellitus, 0) as enfermedad_diabetes_mellitus,
    coalesce(enfermedad_coronaria, 0) as enfermedad_coronaria,
    coalesce(enfermedad_hipertension_arterial, 0) as enfermedad_hipertension_arterial
from {{ ref("silver") }}