services:
  airflow:
    image: criser2013/airflow:slim-3.2.2-python3.13
    build:
      context: .
      dockerfile: airflow.Dockerfile
      args:
        AIRFLOW_VERSION: ${AIRFLOW_VERSION}
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - 8080:8080
    networks:
      - dbt-network
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW_VAR_API_URL: dbt:5000
      AIRFLOW_VAR_LOAD_ENDPOINT: /load-source-data
      AIRFLOW_VAR_RUN_ENDPOINT: /run-dbt
      AIRFLOW_VAR_COMPILE_ENDPOINT: /compile-dbt
      AIRFLOW_WEB_USERNAME: ${AIRFLOW_USERNAME}
      AIRFLOW_WEB_PASSWORD: ${AIRFLOW_PASSWORD}
      AIRFLOW_USER_EMAIL: ${AIRFLOW_USER_EMAIL}
    depends_on:
      postgres:
        condition: service_healthy
      dbt:
        condition: service_healthy

  dbt:
    image: criser2013/dbt:alpine3.21-python3.13.5
    build:
      context: .
      dockerfile: ./api/backend.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dbt-network
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SCHEMA: ${DB_SCHEMA}

  postgres:
    image: postgres:18.4-alpine3.23
    environment:
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_password
      POSTGRES_DB: dbt_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbt_user -d dbt_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - dbt-network

volumes:
  postgres_data:

networks:
  dbt-network:
    driver: bridge